### ISSUE TITLE
"CUDA Error: invalid argument" when use molgrid.GridMaker in multi-GPU setting

### ISSUE THREAD

**Issue by KuNyaa** [gnina/libmolgrid#66]
Hi,

I am currently using the molgrid.GridMaker in our project to convert data to its grid representation. It works well in the single-GPU setting. But when I tried to use Distributed Data Parallel from pytorch to accelerate the training, the molgrid will throw a RuntimeError like this (with a 2 GPUs setting):

```
/opt/tiger/libmolgrid/src/grid_maker.cu:417: invalid argumentTraceback (most recent call last):
  File "main_align.py", line 225, in <module>
    main(args)
  File "main_align.py", line 82, in main
    run_ddp_train(args)
  File "/home/tiger/world/ddp_train_utils.py", line 150, in run_ddp_train
    join=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/tiger/world/ddp_train_utils.py", line 135, in ddp_train_fn
    trainer.train(rank, ddp_model, train_dataset, valid_dataset, evaluator)
  File "/home/tiger/world/engine/trainer.py", line 327, in train
    loss, others = model(batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tiger/world/models/grid_rigid_alignment_prediction.py", line 347, in forward
    grid = self.gmaker(coords, data.types, data.radii, data.batch, to_sparse=False)
  File "/home/tiger/world/models/grid_rigid_alignment_prediction.py", line 331, in gmaker
    grid = Coords2GridFunction.apply(self.grid_maker, (0, 0, 0), coords.to(self.device), types_onehot.to(self.device), radii.to(self.device)).to(self.device)
  File "/usr/local/lib/python3.7/dist-packages/molgrid-0.2.1.dev47+g2375f0b-py3.7.egg/molgrid/torch_bindings.py", line 80, in forward
    gmaker.forward(center, coords, types, radii, output)
RuntimeError: CUDA Error: invalid argument
```

In this code, the "self.grid_maker" is an instance of GridMaker, and "self.device" indicate the rank for each process. This code can work correctly if I change "self.device" to "cpu" (which means only run Coords2GridFunction on cpu and run the rest of the parts on different GPUs), but it will slow down the training. I cannot figure out what is wrong here. Would you like to provide some advice for me? Thanks!

**Comment by dkoes** [comment]
@drewnutt has the most experience with multi-GPU training.  Are the GPUs the same kind of GPU?  You would see this sort of error if one of the cards was older than what is supported.

**Comment by drewnutt** [comment]
I think this may be #43 rearing its head. I presume that this will work if the rank is 0, but not for any rank greater than 0. 

I have been successful with multi-GPU usage when using `torch.DataLoader` and `molgrid.MolDataset`. The only thing I notice that I am doing within each process is setting the default torch device. You may have success if you set the `torch.cuda.set_device(self.device)` within each process.

**Comment by KuNyaa** [comment]
> I think this may be #43 rearing its head. I presume that this will work if the rank is 0, but not for any rank greater than 0.
> 
> I have been successful with multi-GPU usage when using `torch.DataLoader` and `molgrid.MolDataset`. The only thing I notice that I am doing within each process is setting the default torch device. You may have success if you set the `torch.cuda.set_device(self.device)` within each process.

It works for me! Thanks a lot!

**Comment by dkoes** [comment]
@drewnutt Any ideas of how we could produce a more informative error message in this scenario?
